interest-protocol/interest-ui

package.json
src/lib/components/index.ts
src/lib/components/text-field/index.tsx
src/lib/components/text-field/stories/index.stories.tsx
src/lib/components/text-field/text-field.types.ts
src/lib/components/tooltip/index.tsx
src/lib/components/tooltip/stories/index.stories.tsx
src/lib/components/tooltip/tooltip.types.ts

* :sparkles: feat: add tooltip component
* :sparkles: feat: add tooltip component

💄 add tooltip component (#67)

---

src/lib/components/dialog/dialog.data.ts
src/lib/components/dialog/dialog.types.ts
src/lib/components/dialog/dialog.utils.ts
src/lib/components/dialog/index.tsx
src/lib/components/dialog/stories/index.stories.tsx
src/lib/components/progress-indicator/progress-circle.tsx
src/lib/icons/check.tsx
src/lib/icons/exclamation.tsx
src/lib/icons/index.ts
src/lib/icons/warning.tsx

---
- https://app.asana.com/0/0/1206109710798751

:sparkles: feat: modal dialog added

---

package.json
src/lib/components/charts/bar-chart/custom-cursor/custom-cursor.types.ts
src/lib/components/charts/bar-chart/custom-cursor/index.tsx
src/lib/components/charts/bar-chart/index.tsx
src/lib/components/charts/bar-chart/x-axis-tick/index.tsx
src/lib/components/charts/bar-chart/x-axis-tick/x-axis-tick.types.ts
src/lib/components/charts/base-chart.types.ts
src/lib/components/charts/charts.contants.ts
src/lib/components/charts/charts.hooks.ts
src/lib/components/charts/charts.types.ts
src/lib/components/charts/charts.utils.ts
src/lib/components/charts/circle-chart/circle-chart.types.ts
src/lib/components/charts/circle-chart/customized-label/index.tsx
src/lib/components/charts/circle-chart/index.tsx
src/lib/components/charts/index.tsx
src/lib/components/charts/linear-chart/customized-axis-tick/index.tsx
src/lib/components/charts/linear-chart/customized-label/index.tsx
src/lib/components/charts/linear-chart/index.tsx
src/lib/components/charts/steps-chart/index.tsx
src/lib/components/charts/steps-chart/x-axis-tick/index.tsx
src/lib/components/charts/steps-chart/x-axis-tick/x-axis-tick.types.ts
src/lib/components/charts/stories/index.stories.tsx
src/lib/components/charts/tooltip/index.tsx
src/lib/components/charts/tooltip/tooltip.types.ts
yarn.lock

---
- https://app.asana.com/0/0/1206189181392434

:sparkles: charts component

---

src/lib/components/button/index.tsx
src/lib/theme/design-system/radii.ts
src/lib/theme/theme.types.ts
src/lib/theme/variants/button.ts

---
- https://app.asana.com/0/0/1206457724916447

:bug: fix: button focus

---

src/lib/components/dialog/index.tsx
src/lib/components/dialog/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1206685046725479

:bug: Fix export dialog props

---

src/lib/components/token-field/index.tsx
src/lib/components/token-field/stories/index.stories.tsx
src/lib/components/token-field/token-field.types.ts

---
- https://app.asana.com/0/0/1206789771570182

:recycle: Refactor token field props

---

src/lib/components/dialog/index.tsx

---
- https://app.asana.com/0/0/1206901855045487

:bug: Fix dialog width

---

src/lib/components/dropdown-button/index.tsx
src/lib/components/dropdown-button/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029506

🧪 Dropdown test

---

src/lib/components/modal/index.tsx
src/lib/components/modal/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029561

:test_tube: Testing modal

---

package.json
src/lib/components/progress-indicator/index.tsx
src/lib/components/progress-indicator/stories/index.stories.tsx
yarn.lock

---
- https://app.asana.com/0/0/1207089662029567

Progress indicator interactions test

---

src/lib/components/toggle/index.tsx
src/lib/components/toggle/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029589

🧪  Testing toggle

---

src/lib/components/token-field/index.tsx
src/lib/components/token-field/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029595

:test_tube: Add token field interactions test

---

src/lib/components/checkbox/checkbox.types.ts
src/lib/components/checkbox/checkmark.tsx
src/lib/components/checkbox/index.tsx
src/lib/components/checkbox/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029494

:test_tube: Testing checkbox

---

src/lib/components/tabs/index.tsx
src/lib/components/tabs/stories/index.stories.tsx

:test_tube: feat: testing tabs

---

src/lib/components/tooltip/index.tsx
src/lib/components/tooltip/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029601

:test_tube: feat: testing tooltip

---

src/lib/components/radio-button/index.tsx
src/lib/components/radio-button/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029571

:test_tube: testing radio

---

src/lib/components/info-card/index.tsx
src/lib/components/info-card/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029542

:test_tube: testing infoCard

---

src/lib/elements/typography/typography.stories.tsx

---
- https://app.asana.com/0/0/1206135681624105

:test_tube: New testing on typography

---

src/lib/components/toggle/index.tsx
src/lib/components/toggle/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029589

:test_tube: Testing on toggle

---

src/lib/components/tag/index.tsx
src/lib/components/tag/stories/index.stories.tsx
src/lib/components/tag/tag.utils.ts

---
- https://app.asana.com/0/0/1206135681624106

:test_tube: test: testing tag

---

src/lib/components/dialog/index.tsx
src/lib/components/dialog/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029500

:test_tube: Dialogs new test

---

src/lib/components/tabs/index.tsx
src/lib/components/tabs/stories/index.stories.tsx

:test_tube: Testing tabs

---

src/lib/components/radio-button/index.tsx
src/lib/components/radio-button/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029571

:test_tube: Add new radio button test

---

src/lib/components/checkbox/index.tsx
src/lib/components/checkbox/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029494

:test_tube: Add new checkbox test

---

src/lib/components/slider/index.tsx
src/lib/components/slider/range-type.tsx
src/lib/components/slider/slider.types.ts
src/lib/components/slider/slider.utils.ts
src/lib/components/slider/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029575

:test_tube: test: testing slider

---

src/lib/components/toggle/index.tsx
src/lib/components/toggle/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029589

:white_check_mark: Role changed on toggle

---

src/lib/components/modal/index.tsx
src/lib/components/modal/modal-header.tsx
src/lib/components/modal/modal.utils.ts
src/lib/components/modal/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029561

:bug: feat: testing modal

---

src/lib/components/dropdown-button/index.tsx
src/lib/components/dropdown-button/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029506

:test_tube: test: new dropwn test

---

src/lib/components/tag/index.tsx
src/lib/components/tag/stories/index.stories.tsx
src/lib/theme/light/variants/tags.ts

---
- https://app.asana.com/0/0/1206135681624106

:lipstick: Outline focused ui solved

---

src/lib/components/slider/index.tsx
src/lib/components/slider/slider.utils.ts
src/lib/components/slider/stories/index.stories.tsx
src/lib/components/token-field/index.tsx

---
- https://app.asana.com/0/0/1207089662029575

:bug: fix: getbyrole changed to getbylabeltext

---

src/lib/components/tooltip/index.tsx
src/lib/components/tooltip/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029601

:test_tube: test: new test in tooltip

---

src/lib/components/list/index.tsx
src/lib/components/list/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029555

:white_check_mark: Adding test on list

---

src/lib/components/tabs/index.tsx
src/lib/components/tabs/stories/index.stories.tsx

:fire: Role on tabs changed

---

src/lib/elements/typography/index.tsx
src/lib/elements/typography/typography.stories.tsx

---
- https://app.asana.com/0/0/1207956691124653

:bug: fix: typography role

---

src/lib/components/slider/index.tsx
src/lib/components/slider/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029575

:bug: fix: aria label

---

src/lib/components/tag/index.tsx
src/lib/components/tag/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1206135681624106

:white_check_mark: Refactor tag test and acessibility

---

src/lib/components/tooltip/index.tsx
src/lib/components/tooltip/stories/index.stories.tsx
src/lib/components/tooltip/tooltip.types.ts
src/lib/components/tooltip/tooltip.utils.ts

---
- https://app.asana.com/0/0/1207089662029601

:recycle: refactor: adding border and new tests covers

---

src/lib/components/text-field/index.tsx
src/lib/components/text-field/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029583

:test_tube: Add new textfield test

---

src/lib/components/tooltip/index.tsx
src/lib/components/tooltip/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029601

:bug: fix: arrow position

---

src/lib/components/tabs/tab-item.tsx

:white_check_mark: Adding role tab in tab item

---

src/lib/components/tabs/tab-item-text.tsx
src/lib/components/tabs/tab-item.tsx

:white_check_mark: Adding new acessibility props in tabs

---

src/lib/components/progress-indicator/progress-bar.tsx
src/lib/components/progress-indicator/progress-indicator.types.ts
src/lib/components/progress-indicator/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029567

:test_tube: Put progress circle in minimum value

---

src/lib/components/progress-indicator/index.tsx
src/lib/components/progress-indicator/progress-bar.tsx
src/lib/components/progress-indicator/progress-indicator.types.ts
src/lib/components/progress-indicator/progress-indicator.utils.ts
src/lib/components/progress-indicator/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1207089662029567

:lipstick: New style progress bar

---

src/lib/components/token-field/stories/index.stories.tsx

---
- https://app.asana.com/0/0/1208107851906898

✨  Add  token field interactions tests
